### ISSUE TITLE
@ngx-rx-state - Include rxjs-state into bundle 

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/ngx-rx#7]
I consider including rxjs-state into the bundle of ngx-rx-state.

I think it is small enough and would reduce the deep dependencies installation which some ppl forget.

Happy for any opinion!

**Comment by hoebbelsB** [comment]
Will I be able to use the vanilla RxState aswell when just npm i ngx-rx-state with this approach? would be very nice :)

**Comment by BioPhoton** [comment]
Renamed to @ngx-rx/state, deleted vanilla lib
