### ISSUE TITLE
@ngx-rx-state - Rename RxState to RxLocalState

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/ngx-rx#8]
As the vanilla version and the version for the local state in ngx-rx-state have the same name there could be confusion with imports.

A way to fix this could be to rename `RxState` to `RxLocalState`. It would be aligned with the global version `RxGlobalState`.

We would end up with the following;
- @rxjs-state/RxState
- @ngx-rx-state/RxLocalState
- @ngx-rx-state/RxGlobalState

Todos:
- [ ] Rename
- [ ] Tests
- [ ] Docs

**Comment by hoebbelsB** [comment]
kind of sad because RxLocalState is quite a long name to repeat over and over again. Some suggestions:

- NgxRxState
- RxStore
- NgState

**Comment by BioPhoton** [comment]
Ist kind of confusing due to the naming of  rxjs-state's `RxState` class. 
We could think of including the source into the bundle and only expose the Angular parts?
Or hide the export of the vanilla `RxState` class?

**Comment by edbzn** [comment]
I digged a bit in the repo and I feel the naming between packages and folders a bit confusing. At  the first look I don't know what's Angular related and what's RxJS only. I also feel the namespace `ngx-rx-state` quite complicated to remind.

My suggestions: 

- `@rxjs-state/state`
- `@rxjs-state/ng-state`

**Comment by BioPhoton** [comment]
Renamed to @ngx-rx/state
